### ISSUE TITLE
Getting an error on import

### ISSUE THREAD

**Issue by azizsonawalla** [googleapis/nodejs-functions#13]
Got this error at runtime when trying to import the client:

```
TypeError: Cannot read property 'Reader' of undefined
    at /home/asonawalla/github-repos/repo-automation-bots/packages/monitoring-system/data-processor/node_modules/@google-cloud/functions/build/protos/protos.js:28:29
    at /home/asonawalla/github-repos/repo-automation-bots/packages/monitoring-system/data-processor/node_modules/@google-cloud/functions/build/protos/protos.js:22:26
    at Object.<anonymous> (/home/asonawalla/github-repos/repo-automation-bots/packages/monitoring-system/data-processor/node_modules/@google-cloud/functions/build/protos/protos.js:24:3)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/asonawalla/github-repos/repo-automation-bots/packages/monitoring-system/data-processor/node_modules/@google-cloud/functions/build/src/index.js:26:16)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/asonawalla/github-repos/repo-automation-bots/packages/monitoring-system/data-processor/build/src/data-processors/cloud-functions-data-processor.js:19:21)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/asonawalla/github-repos/repo-automation-bots/packages/monitoring-system/data-processor/build/src/data-processor-factory.js:20:42)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/asonawalla/github-repos/repo-automation-bots/packages/monitoring-system/data-processor/build/src/task-service.js:22:34)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/asonawalla/github-repos/repo-automation-bots/packages/monitoring-system/data-processor/build/test/unit/data-processor-factory.spec.js:22:24)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.exports.requireOrImport (/home/asonawalla/github-repos/repo-automation-bots/packages/monitoring-system/data-processor/node_modules/mocha/lib/esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (/home/asonawalla/github-repos/repo-automation-bots/packages/monitoring-system/data-processor/node_modules/mocha/lib/esm-utils.js:33:34)
    at async singleRun (/home/asonawalla/github-repos/repo-automation-bots/packages/monitoring-system/data-processor/node_modules/mocha/lib/cli/run-helpers.js:156:3)
```

Here's the code that I'm trying to run:
```typescript
import {DataProcessor, ProcessorOptions} from './data-processor-abstract';
import {
  CloudFunctionsServiceClient as CloudFunctionClient
} from '@google-cloud/functions';                                         // < -- error thrown right here

export interface CloudFunctionsProcessorOptions extends ProcessorOptions {
  projectId: string;
  location: string;
}

export class CloudFunctionsProcessor extends DataProcessor {
  private projectId: string;
  private location: string;

  constructor(options: CloudFunctionsProcessorOptions) {
    super(options);
    this.functionsClient = new CloudFunctionClient();
    this.projectId = options.projectId;
    this.location = options.location;
  }

  public async collectAndProcess(): Promise<void> {
    throw new Error('Method not implemented.');
  }

  private getAllGCFNames(): string[] {
    throw new Error('Method not implemented.');
  }
}
```
The error seems to be popping up right when it's importing the dependencies, before any of the code even runs. 

Any idea what might be going wrong?

This could totally be me using this library incorrectly

**Comment by JustinBeckwith** [comment]
This basic usage is working:

```js
const {CloudFunctionsServiceClient} = require('@google-cloud/functions');
const client = new CloudFunctionsServiceClient();
async function main() {
  const [fns] = await client.listFunctions({
    parent: client.locationPath('el-gato', 'us-central1'),
  });
  console.log(fns);
}
main();
```

Digging deeper

**Comment by JustinBeckwith** [comment]
Verified this is working with TypeScript as well:

```ts
import {CloudFunctionsServiceClient as CFSC} from '@google-cloud/functions';
const client = new CFSC();
async function main() {
  const [fns] = await client.listFunctions({
    parent: client.locationPath('el-gato', 'us-central1'),
  });
  console.log(fns);
}
main();
```

@azizsonawalla I suspect something else is up here.  Can you check with the latest version of the module?

**Comment by JustinBeckwith** [comment]
Talked it over with @azizsonawalla, this was just a blip 🤷
